![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [2]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[-1.6297284 , -0.54502   , -1.62194039,  0.21950899],
       [-1.02568231, -1.22287873, -3.35638726,  1.38844975],
       [ 0.29573755, -1.474369  , -0.87661759,  0.50263388],
       [ 0.5828061 , -1.80441975, -0.58818259,  1.05593611]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[-2, -2, -2,  2],
       [-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2, -2, -2,  2]])

In [3]:
mrr = np.random.randn(8, 5)
mrr

array([[-1.34471794,  0.33731943,  0.39914503, -0.47037696, -0.40564626],
       [ 1.29618083, -1.03815929,  0.83315143, -0.55814186,  1.17356162],
       [ 0.56517915, -0.54851203, -0.77357922, -0.44345065, -0.25076048],
       [-1.39129509, -0.62718648, -0.04581288, -1.24735983, -0.51222416],
       [ 1.17997266,  1.34030402,  1.02160504, -0.99021568,  0.52092116],
       [ 0.26418999, -1.02043533,  0.17208216, -2.20605697,  0.13597332],
       [ 0.48472173,  0.28578183,  1.16994744,  1.23168495,  0.20617735],
       [-0.89489466, -0.38564637,  1.04616189,  0.80947838,  1.73673012]])

In [5]:
fixed_mrr = np.where(mrr<=0, 0, 1)
fixed_mrr

array([[0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1]])