<a href="https://colab.research.google.com/github/MaxLee77/data-science-lessons/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22mohirdev_NumPy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [ ]:
arr9d = np.zeros((2, 2, 2, 2, 2, 2, 2, 2, 2,))
arr9d

array([[[[[[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]],



           [[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]]],




          [[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]],



           [[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]]]],





         [[[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0.,

`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr4 = np.arange(5, 55, 5)
arr4.dtype

dtype('int64')

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr6 = np.zeros(12)
arr6[5] = 1
arr6

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr7 = np.arange(20, 60)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr8 = np.arange(0, 18, 2)
arr8[::-1]

array([16, 14, 12, 10,  8,  6,  4,  2,  0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr9 = np.arange(12, 21)
arr9 = arr9.reshape(3, 3)
arr9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr10 = np.array([3, 7, 0, 0, 9, 0])
indexs = np.nonzero(arr10)
print(arr10, indexs)

[3 7 0 0 9 0] (array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr11 = np.random.randn(2, 2, 2)
arr11

array([[[-0.16050238,  1.88640804],
        [-0.0036564 ,  1.28161618]],

       [[ 0.67795972,  0.6466334 ],
        [-1.70758088,  0.30377824]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr12 = np.random.randn(9,9)
arr12_max = np.max(arr12)
arr12_min = np.min(arr12)
print(arr12_max, arr12_min)

2.0485806643425786 -2.3459356153440787


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr14_1 = np.random.rand(6, 3)
arr14_2 = np.random.rand(3, 4)
arr14 = np.dot(arr14_1, arr14_2)
arr14

array([[1.11078424, 1.14280698, 1.5819662 , 0.75468489],
       [0.79104865, 0.62513238, 0.59248157, 0.441784  ],
       [0.78211588, 0.86412573, 1.18401322, 0.55746308],
       [0.71521553, 0.91391804, 1.30599093, 0.56723942],
       [1.22273283, 1.31791413, 1.44207501, 0.8417191 ],
       [0.55449056, 0.59447948, 0.74845779, 0.3843799 ]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a16 = np.random.randint(0, 10, (3, 4))
b16 = np.random.randint(0, 10, (3, 4))

print("a16 > b16:\n", a16 > b16, "\n")
print("a16 >= b16:\n", a16 >= b16, "\n")
print("a16 < b16:\n", a16 < b16, "\n")
print("a16 <= b16:\n", a16 <= b16, "\n")


a16 > b16:
 [[False False False False]
 [False  True False False]
 [ True  True False  True]] 

a16 >= b16:
 [[False False  True False]
 [False  True False  True]
 [ True  True False  True]] 

a16 < b16:
 [[ True  True False  True]
 [ True False  True False]
 [False False  True False]] 

a16 <= b16:
 [[ True  True  True  True]
 [ True False  True  True]
 [False False  True False]] 



#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-49-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-49-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-49-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
a18 = np.random.randint(0, 10, (2, 3))
b18 = np.random.randint(0, 10, (2, 3))
arr18 = np.intersect1d(a18, b18)

print("a18 \n", a18, "\n")
print("b18 \n", b18, "\n")
print("Generel value/s \n", arr18)


a18 
 [[1 1 8]
 [6 9 4]] 

b18 
 [[5 0 9]
 [2 4 7]] 

Generel value/s 
 [4 9]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr19 = np.random.uniform(-10, 10, (3, 4))

print("Random numbers\n", arr19, "\n\nIntegrated positive numbers:")
positive_n = arr19[arr19 > 0]

#1
# print(np.floor(positive_n))

#2
# a2 = positive_n.astype(int)
# print(a2)

#3
print(np.trunc(positive_n))


Random numbers
 [[-5.29182276 -0.22289054  8.43158403  9.64140293]
 [-7.52955753  7.61807422  1.229463   -9.21685521]
 [ 3.31154823  3.12462272 -7.69533415  2.32492711]] 

Integrated positive numbers:
[8. 9. 7. 1. 3. 3. 2.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
mat20 = np.arange(0, 2.25, 0.25)
a20 = mat20.reshape(3, 3)
a20

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr21 = np.random.rand(10)
print(np.sort(arr21))

[0.02511277 0.03603941 0.06216412 0.26328831 0.28473688 0.46565029
 0.69284663 0.70719578 0.96434865 0.98759854]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a22 = np.random.randint(-10, 10, (3, 3))
b22 = np.random.randint(-10, 10, (3, 3))

print(np.allclose(a22, b22))
print(np.array_equal(a22, b22))

False
False


  #### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
a23 = np.random.randint(-10, 10, (6, 3))
b23 = np.random.randint(-10, 10, (3, 4))
print("Mtritsa 1\n\n", a23, "\n\n\nMatritsa 2 \n\n", b23, "\n\n\nMtritsalar ko'paytmasi:\n")
print(np.dot(a23, b23))

Mtritsa 1

 [[  8   0  -3]
 [  3   7   6]
 [  5   3  -3]
 [-10  -1   7]
 [ -8   2   7]
 [  5  -1   7]] 


Matritsa 2 

 [[ 0  7  2 -2]
 [ 3  9  5  1]
 [ 3  3 -2  1]] 


Mtritsalar ko'paytmasi:

[[ -9  47  22 -19]
 [ 39 102  29   7]
 [  0  53  31 -10]
 [ 18 -58 -39  26]
 [ 27 -17 -20  25]
 [ 18  47  -9  -4]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
a24 = np.random.uniform(-10, 0, 5)
a24

array([-8.16824967, -7.49784964, -4.56108403, -6.90340293, -6.84461282])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
today = np.datetime64("2025-04-14")
delta = np.timedelta64(1, "D")
yesterday = today - delta
tomorrow = today + delta

print("Yesterday", yesterday, "\nToday", today, "\nTomorrow", tomorrow)

Yesterday 2025-04-13 
Today 2025-04-14 
Tomorrow 2025-04-15


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
dates = np.arange("2016-01-01", "2016-02-01", dtype=np.datetime64)
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
a27 = np.random.uniform(0, 20, (2,3))
print("Original \n", a27, "\n")

#1
b27 = np.floor(a27)
print("Method floor \n", b27, "\n")

#2
c27 = a27.astype(int)
print("Method astype \n", c27, "\n")

#3
d27 = np.trunc(a27)
print("Method trunc \n", d27, "\n")

#4
f27 = a27-(a27 % 1)
print("Method % \n", f27, "\n")



Original 
 [[11.08743188  1.67363695 14.81476883]
 [13.31508553 14.97997278 15.9041367 ]] 

Method floor 
 [[11.  1. 14.]
 [13. 14. 15.]] 

Method astype 
 [[11  1 14]
 [13 14 15]] 

Method trunc 
 [[11.  1. 14.]
 [13. 14. 15.]] 

Method % 
 [[11.  1. 14.]
 [13. 14. 15.]] 



#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
a28 = np.random.randint(0, 100, (2, 3))
b28 = np.random.randint(0, 100, (2, 3))
sum1 = np.add.reduce(a28)
sum2 = np.add.reduce(b28)

print("Original\n", a28, "\n\nsum1\n", sum1, "\n\nsum2\n", sum2)

Original
 [[80 88 21]
 [93  3 28]] 

sum1
 [173  91  49] 

sum2
 [103 144  98]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
a29 = np.array([1,2,3,4,5])
needed_zeros = (len(a29)-1) * 3 + len(a29)
zeros = np.zeros(needed_zeros, dtype = int)
zeros[::4] = a29

print(zeros)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

> Добавить блок с цитатой



In [ ]:
from numpy.lib.stride_tricks import as_strided
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = as_strided(a, shape = (11, 4), strides = (a.strides[0], a.strides[0]))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
bin = np.random.randint(0, 6, 9)
print(bin, "\n", np.bincount(bin))

[5 2 1 3 4 1 0 4 5] 
 [1 2 1 1 2 2]


In [ ]:
arg = np.random.randint(0, 10, (5, 4))
arg
print(arg, np.argmax(arg))

[[5 2 3 5]
 [8 9 0 5]
 [9 7 1 0]
 [0 7 0 1]
 [2 1 1 1]] 5


In [ ]:
arr31 = np.random.randint(0, 10, 15)
argm = argmax(arr31)
binc = np.bincount(arr31)
arg_bin = np.argmax(binc)
print("Original\n", arr31, "\n\nargmax\n", argm, "\n\nbincount\n", binc, "\n\nCombined\n", arg_bin )

Original
 [8 0 1 5 5 1 9 5 4 6 4 8 8 1 7] 

argmax
 6 

bincount
 [1 3 0 0 2 3 1 1 3 1] 

Combined
 1


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
print("Savol:\nNumPy kutubxonasida np.where() funksiyasi yordamida qanday qilib massivdagi manfiy sonlarni 0 bilan almashtirish mumkin?")

Savol:
NumPy kutubxonasida np.where() funksiyasi yordamida qanday qilib massivdagi manfiy sonlarni 0 bilan almashtirish mumkin?


In [ ]:
print("Javob:\nnp.where() shart asosida massiv ichidagi qiymatlarni almashtirish uchun ishlatiladi.\nMisol uchun, agar bizda manfiy va musbat sonlardan iborat massiv bo‘lsa: ")

Javob:
np.where() shart asosida massiv ichidagi qiymatlarni almashtirish uchun ishlatiladi.
Misol uchun, agar bizda manfiy va musbat sonlardan iborat massiv bo‘lsa: 


In [ ]:
# np.where(shart, yangi_qiymat, asl_qiymat)

a = np.array([5, -3, 7, -1, 0, -8, 4])
a_new = np.where(a < 0, 0, a)
print(a_new)

[5 0 7 0 0 0 4]
